# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: mlchain.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='mlchain.proto',
  package='',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=b'\n\rmlchain.proto\x1a\x1bgoogle/protobuf/empty.proto\"\x17\n\x06String\x12\r\n\x05value\x18\x01 \x01(\t\"\x15\n\x04\x42yte\x12\r\n\x05value\x18\x01 \x01(\x0c\"\xaf\x01\n\x07Message\x12\x17\n\x06header\x18\x01 \x01(\x0b\x32\x07.Header\x12\x15\n\rfunction_name\x18\x02 \x01(\t\x12\x0c\n\x04\x61rgs\x18\x03 \x01(\x0c\x12\x0e\n\x06kwargs\x18\x04 \x01(\x0c\x12&\n\x07headers\x18\x05 \x03(\x0b\x32\x15.Message.HeadersEntry\x1a.\n\x0cHeadersEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t:\x02\x38\x01\"1\n\x06Header\x12\x12\n\nserializer\x18\x01 \x01(\t\x12\x13\n\x0bTraceparent\x18\x02 \x01(\x0c\"\x18\n\x06Output\x12\x0e\n\x06output\x18\x02 \x01(\x0c\x32\xb2\x02\n\x0eMLChainService\x12\x1c\n\nget_params\x12\x07.String\x1a\x05.Byte\x12\x1a\n\x08\x64\x65s_func\x12\x07.String\x1a\x05.Byte\x12%\n\x04ping\x12\x16.google.protobuf.Empty\x1a\x05.Byte\x12,\n\x0b\x64\x65scription\x12\x16.google.protobuf.Empty\x1a\x05.Byte\x12\x32\n\x11list_all_function\x12\x16.google.protobuf.Empty\x1a\x05.Byte\x12\x42\n!list_all_function_and_description\x12\x16.google.protobuf.Empty\x1a\x05.Byte\x12\x19\n\x04\x63\x61ll\x12\x08.Message\x1a\x07.Outputb\x06proto3'
  ,
  dependencies=[google_dot_protobuf_dot_empty__pb2.DESCRIPTOR,])




_STRING = _descriptor.Descriptor(
  name='String',
  full_name='String',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='value', full_name='String.value', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=46,
  serialized_end=69,
)


_BYTE = _descriptor.Descriptor(
  name='Byte',
  full_name='Byte',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='value', full_name='Byte.value', index=0,
      number=1, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=b"",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=71,
  serialized_end=92,
)


_MESSAGE_HEADERSENTRY = _descriptor.Descriptor(
  name='HeadersEntry',
  full_name='Message.HeadersEntry',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='key', full_name='Message.HeadersEntry.key', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='value', full_name='Message.HeadersEntry.value', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=b'8\001',
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=224,
  serialized_end=270,
)

_MESSAGE = _descriptor.Descriptor(
  name='Message',
  full_name='Message',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='header', full_name='Message.header', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='function_name', full_name='Message.function_name', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='args', full_name='Message.args', index=2,
      number=3, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=b"",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='kwargs', full_name='Message.kwargs', index=3,
      number=4, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=b"",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='headers', full_name='Message.headers', index=4,
      number=5, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[_MESSAGE_HEADERSENTRY, ],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=95,
  serialized_end=270,
)


_HEADER = _descriptor.Descriptor(
  name='Header',
  full_name='Header',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='serializer', full_name='Header.serializer', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='Traceparent', full_name='Header.Traceparent', index=1,
      number=2, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=b"",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=272,
  serialized_end=321,
)


_OUTPUT = _descriptor.Descriptor(
  name='Output',
  full_name='Output',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='output', full_name='Output.output', index=0,
      number=2, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=b"",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=323,
  serialized_end=347,
)

_MESSAGE_HEADERSENTRY.containing_type = _MESSAGE
_MESSAGE.fields_by_name['header'].message_type = _HEADER
_MESSAGE.fields_by_name['headers'].message_type = _MESSAGE_HEADERSENTRY
DESCRIPTOR.message_types_by_name['String'] = _STRING
DESCRIPTOR.message_types_by_name['Byte'] = _BYTE
DESCRIPTOR.message_types_by_name['Message'] = _MESSAGE
DESCRIPTOR.message_types_by_name['Header'] = _HEADER
DESCRIPTOR.message_types_by_name['Output'] = _OUTPUT
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

String = _reflection.GeneratedProtocolMessageType('String', (_message.Message,), {
  'DESCRIPTOR' : _STRING,
  '__module__' : 'mlchain_pb2'
  # @@protoc_insertion_point(class_scope:String)
  })
_sym_db.RegisterMessage(String)

Byte = _reflection.GeneratedProtocolMessageType('Byte', (_message.Message,), {
  'DESCRIPTOR' : _BYTE,
  '__module__' : 'mlchain_pb2'
  # @@protoc_insertion_point(class_scope:Byte)
  })
_sym_db.RegisterMessage(Byte)

Message = _reflection.GeneratedProtocolMessageType('Message', (_message.Message,), {

  'HeadersEntry' : _reflection.GeneratedProtocolMessageType('HeadersEntry', (_message.Message,), {
    'DESCRIPTOR' : _MESSAGE_HEADERSENTRY,
    '__module__' : 'mlchain_pb2'
    # @@protoc_insertion_point(class_scope:Message.HeadersEntry)
    })
  ,
  'DESCRIPTOR' : _MESSAGE,
  '__module__' : 'mlchain_pb2'
  # @@protoc_insertion_point(class_scope:Message)
  })
_sym_db.RegisterMessage(Message)
_sym_db.RegisterMessage(Message.HeadersEntry)

Header = _reflection.GeneratedProtocolMessageType('Header', (_message.Message,), {
  'DESCRIPTOR' : _HEADER,
  '__module__' : 'mlchain_pb2'
  # @@protoc_insertion_point(class_scope:Header)
  })
_sym_db.RegisterMessage(Header)

Output = _reflection.GeneratedProtocolMessageType('Output', (_message.Message,), {
  'DESCRIPTOR' : _OUTPUT,
  '__module__' : 'mlchain_pb2'
  # @@protoc_insertion_point(class_scope:Output)
  })
_sym_db.RegisterMessage(Output)


_MESSAGE_HEADERSENTRY._options = None

_MLCHAINSERVICE = _descriptor.ServiceDescriptor(
  name='MLChainService',
  full_name='MLChainService',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=350,
  serialized_end=656,
  methods=[
  _descriptor.MethodDescriptor(
    name='get_params',
    full_name='MLChainService.get_params',
    index=0,
    containing_service=None,
    input_type=_STRING,
    output_type=_BYTE,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='des_func',
    full_name='MLChainService.des_func',
    index=1,
    containing_service=None,
    input_type=_STRING,
    output_type=_BYTE,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='ping',
    full_name='MLChainService.ping',
    index=2,
    containing_service=None,
    input_type=google_dot_protobuf_dot_empty__pb2._EMPTY,
    output_type=_BYTE,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='description',
    full_name='MLChainService.description',
    index=3,
    containing_service=None,
    input_type=google_dot_protobuf_dot_empty__pb2._EMPTY,
    output_type=_BYTE,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='list_all_function',
    full_name='MLChainService.list_all_function',
    index=4,
    containing_service=None,
    input_type=google_dot_protobuf_dot_empty__pb2._EMPTY,
    output_type=_BYTE,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='list_all_function_and_description',
    full_name='MLChainService.list_all_function_and_description',
    index=5,
    containing_service=None,
    input_type=google_dot_protobuf_dot_empty__pb2._EMPTY,
    output_type=_BYTE,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='call',
    full_name='MLChainService.call',
    index=6,
    containing_service=None,
    input_type=_MESSAGE,
    output_type=_OUTPUT,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_MLCHAINSERVICE)

DESCRIPTOR.services_by_name['MLChainService'] = _MLCHAINSERVICE

# @@protoc_insertion_point(module_scope)
